name: Build (cabal)

on:
  push:
    branches:
    - master
    - experimental
  pull_request:
    branches:
    - master

jobs:
  cabal:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
        ghc-ver: [9.0.1, 8.10.5, 8.8.4, 8.6.5, 8.4.4, 8.2.2, 8.0.2]
        cabal-ver: [3.4]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc-ver }}
        cabal-version: ${{ matrix.cabal-ver }}
    - run: |
        cabal configure
    - name: Build
      run: |
        cabal build
